name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build debug version of TS with Gradle
      run: ./gradlew :app:assembleGuiDebug :app:assembleBareDebug
    - name: Upload a GUI Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TS-gui-debugBuild
        path: ./app/build/outputs/apk/gui/debug/TS-gui-debug.apk
    - name: Upload a Bare Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TS-bare-debugBuild
        path: ./app/build/outputs/apk/bare/debug/TS-bare-debug.apk